<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            ['name' => 'Paca Alpaca', 'email' => 'pacalaalpaca@gmail.com', 'password' => bcrypt('123456'), 'es_admin' => true],
            ['name' => 'Anna Banana', 'email' => 'anna.banana@gmail.com', 'password' => bcrypt('fruitlove'), 'es_admin' => false],
            ['name' => 'Charlie Churro', 'email' => 'charlie.churro@gmail.com', 'password' => bcrypt('sweetlife'), 'es_admin' => true],
            ['name' => 'Larry Llama', 'email' => 'larry.llama@gmail.com', 'password' => bcrypt('spitfire123'), 'es_admin' => false],
            ['name' => 'Maggie Noodles', 'email' => 'maggie.noodles@gmail.com', 'password' => bcrypt('ramenlife'), 'es_admin' => false],
            ['name' => 'Sally Salami', 'email' => 'sally.salami@gmail.com', 'password' => bcrypt('meatlover123'), 'es_admin' => false],
            ['name' => 'John Doe', 'email' => 'johndoe@gmail.com', 'password' => bcrypt('password7'), 'es_admin' => false],
            ['name' => 'Jane Smith', 'email' => 'janesmith@gmail.com', 'password' => bcrypt('password8'), 'es_admin' => false],
            ['name' => 'Albert Einstein', 'email' => 'einstein@gmail.com', 'password' => bcrypt('password9'), 'es_admin' => false],
            ['name' => 'Marie Curie', 'email' => 'curie@gmail.com', 'password' => bcrypt('password10'), 'es_admin' => false],
            ['name' => 'Bbbbb', 'email' => 'bbbbb@gmail.com', 'password' => bcrypt('123456789'), 'es_admin' => false],
            ['name' => 'Aaaaa', 'email' => 'aaaaa@gmail.com', 'password' => bcrypt('123'), 'es_admin' => true],
        ]);

        DB::table('taula')->insert([
            ['num_taula' => 1, 'estat' => true, 'capacitat' => 4],
            ['num_taula' => 2, 'estat' => false, 'capacitat' => 6],
            ['num_taula' => 3, 'estat' => true, 'capacitat' => 2],
            ['num_taula' => 4, 'estat' => false, 'capacitat' => 8],
            ['num_taula' => 5, 'estat' => true, 'capacitat' => 10],
            ['num_taula' => 6, 'estat' => true, 'capacitat' => 12],
            ['num_taula' => 7, 'estat' => false, 'capacitat' => 3],
            ['num_taula' => 8, 'estat' => false, 'capacitat' => 5],
            ['num_taula' => 9, 'estat' => false, 'capacitat' => 7],
            ['num_taula' => 10, 'estat' => false, 'capacitat' => 4],
        ]);

        DB::table('reserva')->insert([
            ['users_id' => 1, 'taula_id' => 1, 'hora' => now()->addYears(1)->addDays(3)->addHours(2), 'estat' => 'Confirmed', 'num_guests' => 4],
            ['users_id' => 2, 'taula_id' => 3, 'hora' => now()->addYears(2)->addDays(5)->addHours(4), 'estat' => 'Pending', 'num_guests' => 2],
            ['users_id' => 3, 'taula_id' => 5, 'hora' => now()->addYears(3)->addDays(7)->addHours(6), 'estat' => 'Cancelled', 'num_guests' => 5],
            ['users_id' => 4, 'taula_id' => 4, 'hora' => now()->addYears(4)->addDay(1)->addHours(1), 'estat' => 'Confirmed', 'num_guests' => 3],
            ['users_id' => 5, 'taula_id' => 2, 'hora' => now()->addYears(1)->addDays(8)->addHours(8), 'estat' => 'Pending', 'num_guests' => 6],
            ['users_id' => 6, 'taula_id' => 6, 'hora' => now()->addYears(5)->addDays(10)->addHours(10), 'estat' => 'Confirmed', 'num_guests' => 2],
            ['users_id' => 12, 'taula_id' => 1, 'hora' => now()->addYears(6)->addDays(2)->addHours(2), 'estat' => 'Confirmed', 'num_guests' => 4],
            ['users_id' => 12, 'taula_id' => 2, 'hora' => now()->addYears(2)->addDays(5)->addHours(5), 'estat' => 'Pending', 'num_guests' => 3],
            ['users_id' => 12, 'taula_id' => 3, 'hora' => now()->addYears(3)->addDays(4)->addHours(7), 'estat' => 'Confirmed', 'num_guests' => 2],
            ['users_id' => 12, 'taula_id' => 4, 'hora' => now()->addYears(1)->addDays(10)->addHours(9), 'estat' => 'Cancelled', 'num_guests' => 5],
            ['users_id' => 12, 'taula_id' => 5, 'hora' => now()->addYears(2)->addDays(14)->addHours(12), 'estat' => 'Pending', 'num_guests' => 6],
            ['users_id' => 12, 'taula_id' => 6, 'hora' => now()->addYears(4)->addDays(17)->addHours(15), 'estat' => 'Confirmed', 'num_guests' => 8],
            ['users_id' => 12, 'taula_id' => 7, 'hora' => now()->addYears(6)->addDays(19)->addHours(18), 'estat' => 'Pending', 'num_guests' => 2],
        ]);


        DB::table('menu')->insert([
            ['nom' => 'Breakfast Bonanza', 'estat' => true, 'preu_total' => 10.5, 'ingredients_en' => 'Eggs, Bacon, Toast', 'ingredients_ca' => 'Ous, Bacon, Torrades', 'ingredients_es' => 'Huevos, Bacon, Tostadas', 'ingredients_eu' => 'Ohuak, Bacon, Tostada', 'ingredients_fr' => 'Œufs, Bacon, Toast', 'ingredients_de' => 'Eier, Speck, Toast', 'ingredients_it' => 'Uova, Bacon, Toast', 'ingredients_zh' => '鸡蛋, 培根, 烤面包', 'ingredients_ja' => '卵, ベーコン, トースト', 'ingredients_ru' => 'Яйца, Бекон, Тосты'],
            ['nom' => 'Kids’ Happy Meals', 'estat' => true, 'preu_total' => 20.5, 'ingredients_en' => 'Chicken Nuggets, Fries, Apple Slices, Juice', 'ingredients_ca' => 'Nuggets de pollastre, Patates fregides, Tallades de poma, Suc', 'ingredients_es' => 'Nuggets de pollo, Papas fritas, Rodajas de manzana, Jugo', 'ingredients_eu' => 'Txikin Nuggetak, Patatak frijituak, Sagar-uzta, Zukua', 'ingredients_fr' => 'Nuggets de poulet, Frites, Tranches de pomme, Jus', 'ingredients_de' => 'Hähnchen-Nuggets, Pommes, Apfelscheiben, Saft', 'ingredients_it' => 'Nuggets di pollo, Patatine, Fette di mela, Succo', 'ingredients_zh' => '鸡肉块, 薯条, 苹果片, 果汁', 'ingredients_ja' => 'チキンナゲット, フライドポテト, りんごのスライス, ジュース', 'ingredients_ru' => 'Куриные наггетсы, Картошка фри, Ломтики яблок, Сок'],
            ['nom' => 'Weekend Specials', 'estat' => false, 'preu_total' => 15.2, 'ingredients_en' => 'Steak, Mashed Potatoes, Gravy, Vegetables, Bread', 'ingredients_ca' => 'Filet, Puré de patates, Salsa, Verdures, Pa', 'ingredients_es' => 'Bistec, Puré de papas, Salsa, Verduras, Pan', 'ingredients_eu' => 'Esteka, Patata-purea, Saltsa, Barazkiak, Ogia', 'ingredients_fr' => 'Steak, Purée de pommes de terre, Sauce, Légumes, Pain', 'ingredients_de' => 'Steak, Kartoffelpüree, Soße, Gemüse, Brot', 'ingredients_it' => 'Bistecca, Purè di patate, Sugo, Verdure, Pane', 'ingredients_zh' => '牛排, 土豆泥, 肉汁, 蔬菜, 面包', 'ingredients_ja' => 'ステーキ, マッシュポテト, グレービー, 野菜, パン', 'ingredients_ru' => 'Стейк, Картофельное пюре, Соус, Овощи, Хлеб'],
            ['nom' => 'Dessert Dreams', 'estat' => true, 'preu_total' => 18.6, 'ingredients_en' => 'Ice Cream, Chocolate Sauce, Sprinkles', 'ingredients_ca' => 'Gelat, Salsa de xocolata, Sprinkles', 'ingredients_es' => 'Helado, Salsa de chocolate, Sprinkles', 'ingredients_eu' => 'Izotz-krema, Txokolate-saltsa, Sprinkles', 'ingredients_fr' => 'Glace, Sauce au chocolat, Vermicelles', 'ingredients_de' => 'Eis, Schokoladensoße, Streusel', 'ingredients_it' => 'Gelato, Salsa di cioccolato, Codette', 'ingredients_zh' => '冰淇淋, 巧克力酱, 糖果', 'ingredients_ja' => 'アイスクリーム, チョコレートソース, スプリンクル', 'ingredients_ru' => 'Мороженое, Шоколадный соус, Посыпка'],
            ['nom' => 'Healthy Habits', 'estat' => true, 'preu_total' => 25.8, 'ingredients_en' => 'Salad, Grilled Chicken, Avocado, Quinoa, Cherry Tomatoes', 'ingredients_ca' => 'Amanida, Pollastre a la brasa, Alvocat, Quinoa, Tomàquets cherry', 'ingredients_es' => 'Ensalada, Pollo a la parrilla, Aguacate, Quinoa, Tomates cherry', 'ingredients_eu' => 'Entsalada, Pollo parrillatua, Abokatua, Quinoa, Tomate txerria', 'ingredients_fr' => 'Salade, Poulet grillé, Avocat, Quinoa, Tomates cerises', 'ingredients_de' => 'Salat, Gegrilltes Hähnchen, Avocado, Quinoa, Cherrytomaten', 'ingredients_it' => 'Insalata, Pollo alla griglia, Avocado, Quinoa, Pomodori ciliegia', 'ingredients_zh' => '沙拉, 烤鸡肉, 牛油果, 藜麦, 樱桃番茄', 'ingredients_ja' => 'サラダ, グリルチキン, アボカド, キヌア, チェリートマト', 'ingredients_ru' => 'Салат, Курица-гриль, Авокадо, Киноа, Помидоры черри'],
            ['nom' => 'Seafood Sensations', 'estat' => true, 'preu_total' => 28.4, 'ingredients_en' => 'Shrimp, Scallops, Lemon, Garlic, Butter, Parsley', 'ingredients_ca' => 'Gambes, Vieires, Llimona, All, Mantega, Julivert', 'ingredients_es' => 'Camarones, Vieiras, Limón, Ajo, Mantequilla, Perejil', 'ingredients_eu' => 'Kamaroiak, Vieiras, Limona, Baratxuri, Gurina, Perrexil', 'ingredients_fr' => 'Crevettes, Coquilles Saint-Jacques, Citron, Ail, Beurre, Persil', 'ingredients_de' => 'Garnelen, Jakobsmuscheln, Zitrone, Knoblauch, Butter, Petersilie', 'ingredients_it' => 'Gamberi, Capesante, Limone, Aglio, Burro, Prezzemolo', 'ingredients_zh' => '虾, 扇贝, 柠檬, 大蒜, 黄油, 欧芹', 'ingredients_ja' => 'エビ, ホタテ, レモン, ニンニク, バター, パセリ', 'ingredients_ru' => 'Креветки, Гребешки, Лимон, Чеснок, Масло, Петрушка'],
            ['nom' => 'Grill Masters', 'estat' => false, 'preu_total' => 14.0, 'ingredients_en' => 'Burger Patty, Cheese, Lettuce, Tomato, Onion', 'ingredients_ca' => 'Hamburguesa, Formatge, Enciam, Tomàquet, Ceba', 'ingredients_es' => 'Hamburguesa, Queso, Lechuga, Tomate, Cebolla', 'ingredients_eu' => 'Hamburguesa, Gazta, Letxuga, Tomatea, Tipula', 'ingredients_fr' => 'Galette de burger, Fromage, Laitue, Tomate, Oignon', 'ingredients_de' => 'Burger-Patty, Käse, Salat, Tomate, Zwiebel', 'ingredients_it' => 'Hamburger, Formaggio, Lattuga, Pomodoro, Cipolla', 'ingredients_zh' => '汉堡饼, 奶酪, 生菜, 番茄, 洋葱', 'ingredients_ja' => 'ハンバーガーパティ, チーズ, レタス, トマト, 玉ねぎ', 'ingredients_ru' => 'Гамбургер, Сыр, Латук, Помидор, Лук'],
            ['nom' => 'Vegan Vibes', 'estat' => true, 'preu_total' => 26.2, 'ingredients_en' => 'Tofu, Spinach, Kale, Quinoa, Chickpeas, Tahini', 'ingredients_ca' => 'Tofu, Espinacs, Kale, Quinoa, Cigrons, Tahini', 'ingredients_es' => 'Tofu, Espinacas, Kale, Quinoa, Garbanzos, Tahini', 'ingredients_eu' => 'Tofu, Espinakak, Kale, Quinoa, Lekak, Tahini', 'ingredients_fr' => 'Tofu, Épinards, Chou frisé, Quinoa, Pois chiches, Tahini', 'ingredients_de' => 'Tofu, Spinat, Grünkohl, Quinoa, Kichererbsen, Tahini', 'ingredients_it' => 'Tofu, Spinaci, Cavolo riccio, Quinoa, Ceci, Tahini', 'ingredients_zh' => '豆腐, 菠菜, 羽衣甘蓝, 藜麦, 鹰嘴豆, 芝麻酱', 'ingredients_ja' => '豆腐, ほうれん草, ケール, キヌア, ヒヨコ豆, タヒニ', 'ingredients_ru' => 'Тоффу, Шпинат, Кале, Киноа, Нут, Тахини'],
            ['nom' => 'Chef’s Specials', 'estat' => false, 'preu_total' => 30.0, 'ingredients_en' => 'Lobster, Butter Sauce, Asparagus, Herbs', 'ingredients_ca' => 'Llagosta, Salsa de mantega, Espàrrecs, Herbes', 'ingredients_es' => 'Langosta, Salsa de mantequilla, Espárragos, Hierbas', 'ingredients_eu' => 'Krisalu, Gurina, Esparragoak, Belar', 'ingredients_fr' => 'Homard, Sauce au beurre, Asperges, Herbes', 'ingredients_de' => 'Hummer, Buttersauce, Spargel, Kräuter', 'ingredients_it' => 'Aragosta, Salsa al burro, Asparagi, Erbe', 'ingredients_zh' => '龙虾, 黄油酱, 芦笋, 香草', 'ingredients_ja' => 'ロブスター, バターソース, アスパラガス, ハーブ', 'ingredients_ru' => 'Лобстер, Масляный соус, Спаржа, Травы'],
            ['nom' => 'Midnight Munchies', 'estat' => false, 'preu_total' => 12.8, 'ingredients_en' => 'Pizza, Garlic Bread, Mozzarella, Olives, Pepperoni', 'ingredients_ca' => 'Pizza, Pa d’all, Mozzarella, Olives, Pepperoni', 'ingredients_es' => 'Pizza, Pan de ajo, Mozzarella, Aceitunas, Pepperoni', 'ingredients_eu' => 'Pizza, Baratxuri-ogia, Mozzarella, Oliba, Pepperoni', 'ingredients_fr' => 'Pizza, Pain à l’ail, Mozzarella, Olives, Pepperoni', 'ingredients_de' => 'Pizza, Knoblauchbrot, Mozzarella, Oliven, Pepperoni', 'ingredients_it' => 'Pizza, Pane all’aglio, Mozzarella, Olive, Pepperoni', 'ingredients_zh' => '披萨, 大蒜面包, 莫扎里拉, 橄榄, 意大利辣香肠', 'ingredients_ja' => 'ピザ, ガーリックブレッド, モッツァレラ, オリーブ, ペパロニ', 'ingredients_ru' => 'Пицца, Чесночный хлеб, Моцарелла, Оливки, Пепперони']
        ]);

        DB::table('comanda')->insert([
            ['users_id' => 1, 'menu_id' => 1, 'quantitat' => 2, 'preu_total' => 21.00, 'estat' => 'Completed'],
            ['users_id' => 2, 'menu_id' => 3, 'quantitat' => 1, 'preu_total' => 15.20, 'estat' => 'Pending'],
            ['users_id' => 3, 'menu_id' => 4, 'quantitat' => 3, 'preu_total' => 55.80, 'estat' => 'Completed'],
            ['users_id' => 4, 'menu_id' => 5, 'quantitat' => 1, 'preu_total' => 25.80, 'estat' => 'Cancelled'],
            ['users_id' => 5, 'menu_id' => 2, 'quantitat' => 5, 'preu_total' => 102.50, 'estat' => 'Completed'],
            ['users_id' => 6, 'menu_id' => 6, 'quantitat' => 2, 'preu_total' => 56.80, 'estat' => 'Completed'],
            ['users_id' => 7, 'menu_id' => 8, 'quantitat' => 4, 'preu_total' => 103.20, 'estat' => 'Pending'],
            ['users_id' => 8, 'menu_id' => 9, 'quantitat' => 1, 'preu_total' => 18.60, 'estat' => 'Completed'],
            ['users_id' => 9, 'menu_id' => 7, 'quantitat' => 2, 'preu_total' => 56.80, 'estat' => 'Pending'],
            ['users_id' => 10, 'menu_id' => 10, 'quantitat' => 1, 'preu_total' => 30.00, 'estat' => 'Completed'],
            ['users_id' => 12, 'menu_id' => 1, 'quantitat' => 2, 'preu_total' => 21.00, 'estat' => 'Completed'],
            ['users_id' => 12, 'menu_id' => 5, 'quantitat' => 3, 'preu_total' => 77.40, 'estat' => 'Pending'],
            ['users_id' => 12, 'menu_id' => 7, 'quantitat' => 1, 'preu_total' => 15.50, 'estat' => 'Completed'],
            ['users_id' => 12, 'menu_id' => 9, 'quantitat' => 4, 'preu_total' => 60.00, 'estat' => 'Pending'],
            ['users_id' => 12, 'menu_id' => 3, 'quantitat' => 2, 'preu_total' => 22.00, 'estat' => 'Completed'],
            ['users_id' => 12, 'menu_id' => 6, 'quantitat' => 5, 'preu_total' => 125.00, 'estat' => 'Completed'],
            ['users_id' => 12, 'menu_id' => 4, 'quantitat' => 1, 'preu_total' => 19.90, 'estat' => 'Pending'],
        ]);


        DB::table('resenya')->insert([
            ['users_id' => 1, 'menu_id' => 1, 'puntuacio' => 5, 'comentari_en' => 'A delicious breakfast, the pancakes were fluffy and the eggs were perfect!', 'comentari_ca' => 'Un esmorzar deliciós, les pancakes eren esponjoses i els ous eren perfectes!', 'comentari_es' => 'Un desayuno delicioso, los panqueques eran esponjosos y los huevos estaban perfectos!', 'comentari_eu' => 'Hamaiketako goxoa, panquequeek flufy ziren eta arrautzak perfektuak!', 'comentari_fr' => 'Un petit-déjeuner délicieux, les pancakes étaient moelleux et les œufs parfaits!', 'comentari_de' => 'Ein köstliches Frühstück, die Pfannkuchen waren fluffig und die Eier perfekt!', 'comentari_it' => 'Una colazione deliziosa, i pancake erano soffici e le uova perfette!', 'comentari_zh' => '美味的早餐，煎饼松软，鸡蛋完美！', 'comentari_ja' => 'おいしい朝食、パンケーキはふわふわで、卵は完璧でした！', 'comentari_ru' => 'Вкусный завтрак, блины были воздушные, а яйца идеальные!'],
            ['users_id' => 2, 'menu_id' => 3, 'puntuacio' => 3, 'comentari_en' => 'The sundae was heavenly, but the salad could have been fresher.', 'comentari_ca' => "El sundae era celestial, però l'amanida podria haver estat més fresca.", 'comentari_es' => 'El helado era celestial, pero la ensalada podría haber estado más fresca.', 'comentari_eu' => 'Sundae-a zerutegia zen, baina entsalada freskagoa izan zitekeen.', 'comentari_fr' => 'Le sundae était divin, mais la salade aurait pu être plus fraîche.', 'comentari_de' => 'Das Eis war himmlisch, aber der Salat hätte frischer sein können.', 'comentari_it' => 'Il gelato era divino, ma l’insalata avrebbe potuto essere più fresca.', 'comentari_zh' => '圣代是天堂般的，但沙拉本可以更新鲜一点。', 'comentari_ja' => 'サンデーは天国のようでしたが、サラダはもう少し新鮮だったかもしれません。', 'comentari_ru' => 'Суффле было божественным, но салат мог бы быть свежее.'],
            ['users_id' => 3, 'menu_id' => 4, 'puntuacio' => 4, 'comentari_en' => 'Great pizza and fries, but the falafel was a bit dry.', 'comentari_ca' => 'Molt bona pizza i patates fregides, però el falafel estava una mica sec.', 'comentari_es' => 'Muy buena pizza y papas fritas, pero el falafel estaba un poco seco.', 'comentari_eu' => 'Pizza eta patata frijituak bikainak, baina falafel-a pixka bat lehorra zegoen.', 'comentari_fr' => 'Très bonne pizza et frites, mais le falafel était un peu sec.', 'comentari_de' => 'Großartige Pizza und Pommes, aber der Falafel war etwas trocken.', 'comentari_it' => 'Ottima pizza e patatine, ma il falafel era un po’ secco.', 'comentari_zh' => '很棒的披萨和薯条，但法拉费尔有点干。', 'comentari_ja' => '素晴らしいピザとフライドポテトでしたが、ファラフェルは少し乾燥していました。', 'comentari_ru' => 'Отличная пицца и картошка фри, но фалафель был немного сухим.'],
            ['users_id' => 4, 'menu_id' => 5, 'puntuacio' => 4, 'comentari_en' => 'The vegan bowl was perfect, but the lobster could have been cooked better.', 'comentari_ca' => 'El bol vegà era perfecte, però la llagosta es podria haver cuinat millor.', 'comentari_es' => 'El bol vegano era perfecto, pero la langosta podría haberse cocinado mejor.', 'comentari_eu' => 'Bol veganoa perfektua zen, baina krisaluak hobeto egos zitezkeen.', 'comentari_fr' => 'Le bol vegan était parfait, mais le homard aurait pu être mieux cuit.', 'comentari_de' => 'Die vegane Bowl war perfekt, aber der Hummer hätte besser gekocht sein können.', 'comentari_it' => 'La ciotola vegana era perfetta, ma l’aragosta avrebbe potuto essere cucinata meglio.', 'comentari_zh' => '素食碗完美，但龙虾可以煮得更好。', 'comentari_ja' => 'ヴィーガンボウルは完璧でしたが、ロブスターはもう少し上手に調理されていたかもしれません。', 'comentari_ru' => 'Веганская чаша была идеальной, но омар мог бы быть приготовлен лучше.'],
            ['users_id' => 5, 'menu_id' => 2, 'puntuacio' => 3, 'comentari_en' => 'My kids loved the tacos, but the burger was a bit too greasy.', 'comentari_ca' => "A els meus nens els van encantar els tacos, però la hamburguesa estava una mica massa greixosa.", 'comentari_es' => 'A mis hijos les encantaron los tacos, pero la hamburguesa estaba un poco grasosa.', 'comentari_eu' => 'Nire haurrek tacos-ak maite zituzten, baina hamburguesa pixka bat olioz beteta zegoen.', 'comentari_fr' => 'Mes enfants ont adoré les tacos, mais le burger était un peu trop gras.', 'comentari_de' => 'Meine Kinder liebten die Tacos, aber der Burger war etwas zu fettig.', 'comentari_it' => 'I miei bambini hanno adorato i tacos, ma l’hamburger era un po’ troppo grasso.', 'comentari_zh' => '我的孩子们喜欢塔可，但汉堡有点太油腻了。', 'comentari_ja' => '子供たちはタコスが大好きでしたが、ハンバーガーは少し脂っこすぎました。', 'comentari_ru' => 'Моим детям понравились такос, но бургер был немного жирным.'],
            ['users_id' => 6, 'menu_id' => 6, 'puntuacio' => 4, 'comentari_en' => 'The sushi was fresh and tasty, but perhaps too much wasabi.', 'comentari_ca' => 'El sushi estava fresc i saborós, però potser massa wasabi.', 'comentari_es' => 'El sushi estaba fresco y sabroso, pero tal vez demasiado wasabi.', 'comentari_eu' => 'Sushi freskoa eta goxoa zen, baina agian wasabi gehiegi zegoen.', 'comentari_fr' => 'Le sushi était frais et savoureux, mais peut-être trop de wasabi.', 'comentari_de' => 'Das Sushi war frisch und lecker, aber vielleicht zu viel Wasabi.', 'comentari_it' => 'Il sushi era fresco e gustoso, ma forse troppo wasabi.', 'comentari_zh' => '寿司新鲜美味，但可能酱油有点多。', 'comentari_ja' => '寿司は新鮮でおいしかったが、ワサビが多すぎたかもしれません。', 'comentari_ru' => 'Суши были свежими и вкусными, но, возможно, было слишком много васаби.'],
            ['users_id' => 7, 'menu_id' => 8, 'puntuacio' => 5, 'comentari_en' => 'Amazing vegan dishes! The mac and tuna tartare were fantastic!', 'comentari_ca' => 'Dishes vegans increïbles! El mac i el tàrtar de tonyina eren fantàstics!', 'comentari_es' => '¡Platos veganos increíbles! ¡El mac y el tartar de atún eran fantásticos!', 'comentari_eu' => 'Plater veganik izugarriak! Mac eta atun tartarra ziren zoragarriak!', 'comentari_fr' => 'Plats végétaliens incroyables! Les macaronis et le tartare de thon étaient fantastiques!', 'comentari_de' => 'Erstaunliche vegane Gerichte! Der Mac und das Thunfisch-Tatar waren fantastisch!', 'comentari_it' => 'Piatti vegani incredibili! Il mac e il tartare di tonno erano fantastici!', 'comentari_zh' => '惊人的素食菜肴！意大利面和金枪鱼塔塔酱非常棒！', 'comentari_ja' => '素晴らしいヴィーガン料理！マックとツナタルタルは素晴らしかった！', 'comentari_ru' => 'Удивительные веганские блюда! Мак и тартар из тунца были фантастическими!'],
            ['users_id' => 8, 'menu_id' => 9, 'puntuacio' => 3, 'comentari_en' => 'The Banh Mi and steak were great, but I didn’t enjoy the fajitas as much.', 'comentari_ca' => "El Banh Mi i l’entrecot eren genials, però no vaig gaudir tant de les fajites.", 'comentari_es' => 'El Banh Mi y el entrecot eran geniales, pero no disfruté tanto las fajitas.', 'comentari_eu' => 'Banh Mi eta entrekote bikainak ziren, baina fajitak ez nituen hainbeste gustatu.', 'comentari_fr' => 'Le Banh Mi et le steak étaient géniaux, mais je n’ai pas autant apprécié les fajitas.', 'comentari_de' => 'Das Banh Mi und das Steak waren großartig, aber die Fajitas haben mir nicht so gut gefallen.', 'comentari_it' => 'Il Banh Mi e la bistecca erano fantastici, ma non mi sono piaciute tanto le fajitas.', 'comentari_zh' => 'Banh Mi 和牛排很棒，但我没有那么喜欢墨西哥卷饼。', 'comentari_ja' => 'バインミーとステーキは素晴らしかったですが、ファヒータはあまり楽しめませんでした。', 'comentari_ru' => 'Banh Mi и стейк были отличными, но фахитас мне не понравились.'],
            ['users_id' => 9, 'menu_id' => 7, 'puntuacio' => 4, 'comentari_en' => 'The chicken parmesan was juicy, but the pad Thai was too spicy.', 'comentari_ca' => "El pollastre parmesà estava jugós, però el pad Thai estava massa picant.", 'comentari_es' => 'El pollo parmesano estaba jugoso, pero el pad Thai estaba demasiado picante.', 'comentari_eu' => 'Pollo parmesanoa zukutsua zen, baina pad Thaik gehiegi pikatu zuen.', 'comentari_fr' => 'Le poulet parmesan était juteux, mais le pad thaï était trop épicé.', 'comentari_de' => 'Das Hühnchen-Parmesan war saftig, aber das Pad Thai war zu scharf.', 'comentari_it' => 'Il pollo alla parmigiana era succoso, ma il pad Thai era troppo piccante.', 'comentari_zh' => '鸡肉帕尔玛干酪多汁，但泰式炒河粉太辣了。', 'comentari_ja' => 'チキンパルメザンはジューシーでしたが、パッタイは辛すぎました。', 'comentari_ru' => 'Курица по-пармезански была сочной, но падтай был слишком острым.'],
            ['users_id' => 10, 'menu_id' => 10, 'puntuacio' => 5, 'comentari_en' => 'Excellent midnight snacks, loved the duck and ribs.', 'comentari_ca' => 'Excel·lents entrepans de mitjanit, vaig adorar el ànec i les costelles.', 'comentari_es' => 'Excelentes bocadillos de medianoche, me encantaron el pato y las costillas.', 'comentari_eu' => 'Gaiztoak bikainak, maite izan nuen antzarra eta gibelak.', 'comentari_fr' => 'Excellents snacks de minuit, j’ai adoré le canard et les côtes.', 'comentari_de' => 'Ausgezeichnete Mitternachtssnacks, ich liebte die Ente und die Rippen.', 'comentari_it' => 'Ottimi spuntini di mezzanotte, ho adorato l’anatra e le costine.', 'comentari_zh' => '极好的午夜小吃，喜欢鸭肉和肋骨。', 'comentari_ja' => '素晴らしい真夜中のおやつ、アヒル肉とリブが大好きでした。', 'comentari_ru' => 'Отличные полночные закуски, мне понравились утка и ребра.'],
            ['users_id' => 12, 'menu_id' => 1, 'puntuacio' => 4, 'comentari_en' => 'Good meal, the eggs were cooked well, but the toast was a bit dry.', 'comentari_ca' => 'Bon àpat, els ous estaven ben cuits, però les torrades estaven una mica seques.', 'comentari_es' => 'Buena comida, los huevos estaban bien cocidos, pero las tostadas estaban un poco secas.', 'comentari_eu' => 'Bazkari ona, arrautzak ondo egosiak ziren, baina torradak pixka bat lehor egon ziren.', 'comentari_fr' => 'Bon repas, les œufs étaient bien cuits, mais les toasts étaient un peu secs.', 'comentari_de' => 'Gutes Essen, die Eier waren gut gekocht, aber das Toast war etwas trocken.', 'comentari_it' => 'Buon pasto, le uova erano ben cotte, ma le fette di pane erano un po’ secche.', 'comentari_zh' => '美味的餐点，鸡蛋煮得很好，但烤面包有点干。', 'comentari_ja' => '良い食事、卵はうまく調理されていましたが、トーストは少し乾燥していました。', 'comentari_ru' => 'Хорошая еда, яйца были хорошо приготовлены, но тосты были немного сухими。'],
            ['users_id' => 12, 'menu_id' => 5, 'puntuacio' => 5, 'comentari_en' => 'The vegan bowl was delicious, everything was perfectly cooked!', 'comentari_ca' => 'El bol vegà estava deliciós, tot estava perfectament cuinat!', 'comentari_es' => 'El bol vegano estaba delicioso, todo estaba perfectamente cocinado!', 'comentari_eu' => 'Bol veganoa goxoa zen, guztia perfektu egina zegoen!', 'comentari_fr' => 'Le bol végétalien était délicieux, tout était parfaitement cuit!', 'comentari_de' => 'Die vegane Bowl war köstlich, alles war perfekt gekocht!', 'comentari_it' => 'La ciotola vegana era deliziosa, tutto era cucinato perfettamente!', 'comentari_zh' => '素食碗非常美味，一切都煮得恰到好处！', 'comentari_ja' => 'ヴィーガンボウルは美味しく、すべてが完璧に調理されていました！', 'comentari_ru' => 'Веганская чаша была вкусной, все было идеально приготовлено!'],
            ['users_id' => 12, 'menu_id' => 3, 'puntuacio' => 3, 'comentari_en' => 'The pasta was okay, but it was a bit too salty for my taste.', 'comentari_ca' => 'La pasta estava bé, però estava una mica massa salada per al meu gust.', 'comentari_es' => 'La pasta estaba bien, pero estaba un poco demasiado salada para mi gusto.', 'comentari_eu' => 'Pasta ona zen, baina nire gusturako gehiegi gazi egon zen.', 'comentari_fr' => 'Les pâtes étaient bien, mais elles étaient un peu trop salées à mon goût.', 'comentari_de' => 'Die Pasta war in Ordnung, aber für meinen Geschmack war sie etwas zu salzig.', 'comentari_it' => 'La pasta era buona, ma per i miei gusti era un po’ troppo salata.', 'comentari_zh' => '意大利面还可以，但对我来说有点太咸了。', 'comentari_ja' => 'パスタはまあまあでしたが、私の好みでは少し塩辛かったです。', 'comentari_ru' => 'Паста была нормальной, но для моего вкуса она была немного слишком соленой。'],
            ['users_id' => 12, 'menu_id' => 9, 'puntuacio' => 5, 'comentari_en' => 'The dessert was amazing! Sweet but not overly sugary, just perfect.', 'comentari_ca' => 'El postres va ser increïble! Dolç però no massa ensucrat, perfecte.', 'comentari_es' => '¡El postre fue increíble! Dulce pero no demasiado azucarado, perfecto.', 'comentari_eu' => 'Postrea zoragarria izan zen! Gozoki, baina ez gehiegi azukreduna, perfektua.', 'comentari_fr' => 'Le dessert était incroyable! Doux mais pas trop sucré, juste parfait.', 'comentari_de' => 'Das Dessert war erstaunlich! Süß, aber nicht zu zuckerhaltig, einfach perfekt.', 'comentari_it' => 'Il dessert era fantastico! Dolce ma non troppo zuccherato, perfetto.', 'comentari_zh' => '甜点真棒！甜而不腻，恰到好处。', 'comentari_ja' => 'デザートは素晴らしかった！甘いけれども過剰に砂糖を使っていなくて、ちょうど良いです。', 'comentari_ru' => 'Десерт был потрясающим! Сладкий, но не слишком сахарный, просто идеально!'],
            ['users_id' => 12, 'menu_id' => 6, 'puntuacio' => 2, 'comentari_en' => 'The soup was a bit bland and needed more seasoning.', 'comentari_ca' => 'La sopa era una mica insípida i necessitava més condiments.', 'comentari_es' => 'La sopa estaba un poco insípida y necesitaba más condimentos.', 'comentari_eu' => 'Sopa pixka bat zurrunbilo zen eta gehiago zaporetu behar zuen.', 'comentari_fr' => 'La soupe était un peu fade et avait besoin de plus d’assaisonnement.', 'comentari_de' => 'Die Suppe war etwas fad und brauchte mehr Gewürze.', 'comentari_it' => 'La zuppa era un po’ insipida e aveva bisogno di più condimenti.', 'comentari_zh' => '汤有点寡淡，需要更多调味料。', 'comentari_ja' => 'スープは少し味が薄く、もっと調味料が必要でした。', 'comentari_ru' => 'Суп был немного пресным и требовал больше приправ。'],
        ]);
    }
}
